package com.example.ammacias.juegomarcas.localdb;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.ammacias.juegomarcas.localdb.MarcaDB;

import com.example.ammacias.juegomarcas.localdb.MarcaDBDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig marcaDBDaoConfig;

    private final MarcaDBDao marcaDBDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        marcaDBDaoConfig = daoConfigMap.get(MarcaDBDao.class).clone();
        marcaDBDaoConfig.initIdentityScope(type);

        marcaDBDao = new MarcaDBDao(marcaDBDaoConfig, this);

        registerDao(MarcaDB.class, marcaDBDao);
    }
    
    public void clear() {
        marcaDBDaoConfig.getIdentityScope().clear();
    }

    public MarcaDBDao getMarcaDBDao() {
        return marcaDBDao;
    }

}
