package com.example.ammacias.juegomarcas.localdb;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "MARCA_DB".
*/
public class MarcaDBDao extends AbstractDao<MarcaDB, Long> {

    public static final String TABLENAME = "MARCA_DB";

    /**
     * Properties of entity MarcaDB.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Nombre = new Property(1, String.class, "nombre", false, "NOMBRE");
        public final static Property Nivel = new Property(2, int.class, "nivel", false, "NIVEL");
        public final static Property Foto = new Property(3, String.class, "foto", false, "FOTO");
        public final static Property Acertado = new Property(4, boolean.class, "acertado", false, "ACERTADO");
    };


    public MarcaDBDao(DaoConfig config) {
        super(config);
    }
    
    public MarcaDBDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"MARCA_DB\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"NOMBRE\" TEXT NOT NULL ," + // 1: nombre
                "\"NIVEL\" INTEGER NOT NULL ," + // 2: nivel
                "\"FOTO\" TEXT NOT NULL ," + // 3: foto
                "\"ACERTADO\" INTEGER NOT NULL );"); // 4: acertado
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"MARCA_DB\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, MarcaDB entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getNombre());
        stmt.bindLong(3, entity.getNivel());
        stmt.bindString(4, entity.getFoto());
        stmt.bindLong(5, entity.getAcertado() ? 1L: 0L);
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, MarcaDB entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getNombre());
        stmt.bindLong(3, entity.getNivel());
        stmt.bindString(4, entity.getFoto());
        stmt.bindLong(5, entity.getAcertado() ? 1L: 0L);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public MarcaDB readEntity(Cursor cursor, int offset) {
        MarcaDB entity = new MarcaDB( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // nombre
            cursor.getInt(offset + 2), // nivel
            cursor.getString(offset + 3), // foto
            cursor.getShort(offset + 4) != 0 // acertado
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, MarcaDB entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setNombre(cursor.getString(offset + 1));
        entity.setNivel(cursor.getInt(offset + 2));
        entity.setFoto(cursor.getString(offset + 3));
        entity.setAcertado(cursor.getShort(offset + 4) != 0);
     }
    
    @Override
    protected final Long updateKeyAfterInsert(MarcaDB entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(MarcaDB entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
